### ISSUE TITLE
Player display issues

### ISSUE THREAD

**Issue by mvmalyi** [fer0n/Unwatched#1]
Videos in the queue from different channels have different player display. While everything is alright with minutephysics:
![image](https://github.com/user-attachments/assets/593bc53a-82b3-4bda-b118-819f33a301f0)

A video from BigThink displays YouTube's web interface together with the app's player interface:
![image](https://github.com/user-attachments/assets/2b7137ab-6094-4821-bfe2-fd432abed4d0)

Horizontal layout for minutephysics:
![image](https://github.com/user-attachments/assets/018943ea-e3b8-45cb-8f97-9641b61b38e2)

And for BigThink:
![image](https://github.com/user-attachments/assets/442e2a18-0e58-42c2-8adb-9a9b9d1600f6)

**Comment by fer0n** [comment]
Thanks for your feedback :)

Unwatched is using the [YouTube iframe player](https://developers.google.com/youtube/iframe_api_reference) to play videos. Channels can opt-out of making all or individual videos available for embeddings.

For the channels that don't allow embeddings, the player falls back to showing the YouTube website. You can still enter fullscreen for those videos; Picture-in-picture, as well as the controls should still be working. This is sadly a technical limitation.
