### ISSUE TITLE
Anbindung an Shortcuts

### ISSUE THREAD

**Issue by demed86** [fer0n/Unwatched#10]
Hi, erstmal vielen Dank für diese tolle App. Ist bei mir der neue Standard. 

Frage: Gibt es eine Möglichkeit über die App ShortCut von Apple Videos/Playlists einzufügen? Aktuell kopiere ich den Link und füge ihn ein.

**Comment by fer0n** [comment]
Freut mich :) 
Unwatched hat bereits eine shortcut Aktion um Videos zur Queue hinzuzufügen.

Entweder direkt in der shortcuts App oder über Bibliothek → Einstellungen (Zahnrad links oben) → Share sheet setup.

Bei Fragen einfach Bescheid sagen.
