### ISSUE TITLE
iPad Status Bar During Fullscreen Playback

### ISSUE THREAD

**Issue by potatoDOTzip** [fer0n/Unwatched#11]
When playing a video in fullscreen on iPad, the status bar (clock, date, battery, etc.) remains visible. Perhaps a setting could be added to hide it during fullscreen playback.
![Friday, 20 Sep 2024 17:10:34](https://github.com/user-attachments/assets/6f9d01b9-d710-4734-8a3b-31fda40591af)

**Comment by fer0n** [comment]
That's a fair point, I'll look into it. Same goes for the home indicator. 

In the meantime, you can use the native iOS fullscreen (tap on the fullscreen icon inside the YouTube player).

**Comment by fer0n** [comment]
Will be in the next version
