### ISSUE TITLE
New videos don't show up in the subscrptions

### ISSUE THREAD

**Issue by swj1442291549** [fer0n/Unwatched#12]
Certain subscriptions do not show latest videos in the inbox or its own setting window.

I try to directly open the youtube rss feed url, sometimes I got a message like this: "We're sorry...
... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now. See [Google Help](https://support.google.com/websearch/answer/86640) for more information." I wonder whether this is due to high frequency query.

For your information, I have 77 subscriptions.

**Comment by fer0n** [comment]
And I'm assuming the "not showing up" issue is just the fact that the rss feed refuses to refresh the data?

**Comment by swj1442291549** [comment]
I guess so. If my change my ip and retry that rss feed, I can see the latest videos in the browser. However if I click the refresh button on the top-right corner in Library tab, nothing would happen (even with a global proxy).

**Comment by swj1442291549** [comment]
I am not sure whether this is working. Right now, the rss feed is not blocked. But looking into the backup data, there is something I don't understand.

So here is feed I never get an update:
```
{
      "title": "睡前消息",
      "subscribedDate": 748962628.691339,
      "youtubeUserName": "ProletariatsBishop",
      "placeVideosIn": 1,
      "mostRecentVideoDate": 749133395,
      "isArchived": false,
      "youtubeChannelId": "UCR4U_q_MojVVqYnawAVlryw",
      "link": "https://www.youtube.com/feeds/videos.xml?channel_id=UCR4U_q_MojVVqYnawAVlryw",
      "thumbnailUrl": "https://yt3.googleusercontent.com/IqGQPAzadxyE5cssvXpOYobdnC9N9OSdq5sHU0L6HrupyD_egJSHRQZvFcIoqO6qw5Cgn8pS=s900-c-k-c0x00ffffff-no-rj",
      "videosIds": [
        -5400485789682278000,
        1836851103427169300
      ]
    },
```
You see I just try to fetch the feed (based on `mostRecentVideoDate`), but there are only two videosID in the list and the latest few are not included.

**Comment by fer0n** [comment]
This is only the backup data though, depending on your settings this might not include all videos that are actually in the app. The `mostRecentVideoDate` is only the cut off date to decide which videos to add to the inbox/queue.

Have you tried to turn off auto refresh and background fetch?

Could you also try to reload directly on the subscription page for that channel? Perhaps the refresh is running out of memory in the background and silently failing.

If you can, a screenshot of the failed rss feed fetch would also be helpful.

**Comment by swj1442291549** [comment]
I have turned off the auto refresh and background fetch and I don't see error message when accessed through browser. I do not know how to check that in the app, I never saw an error there.

I have tried to directly reload the subscription page for that channel (I am assuming this means clicking the sync button in the channel, see red circle on the attached). But as I said, just a cloud icon show up for a few second and then disappear. No new videos appears in the list.

I am not sure the attached is the screenshot you want, but I am happy to share more information If I know how to do it.


![Screenshot 2024-09-27 at 20 09 24](https://github.com/user-attachments/assets/6ca6f9fb-9e9a-465f-8daf-060d0c49b832)

**Comment by fer0n** [comment]
I may have found a fix or at the very least an improvement for this. Would you mind trying the latest build? (141)

https://testflight.apple.com/join/9RP0WzCR

**Comment by fer0n** [comment]
Could you also check if the Chinese text input is working?

**Comment by swj1442291549** [comment]
Yes, it's working.

**Comment by fer0n** [comment]
The text input or the new videos?

**Comment by swj1442291549** [comment]
The text input.

**Comment by fer0n** [comment]
And the video refresh, were you able to test it?

**Comment by swj1442291549** [comment]
The Same issue. I never see that new videos of that feed appear (but on youtube website, the latest one is one day ago. )

**Comment by fer0n** [comment]
On build 141?

**Comment by swj1442291549** [comment]
Unfortunately yes.

I wonder whether it's possible to know what has been fetched for that feed. So we can pin down where the problem is. As you mentioned, the backup date might not be reliable for this purpose.

**Comment by fer0n** [comment]
I'll see if I can add an option to share logs. Would you be willing to share a backup file? Perhaps I can reproduce the issue myself that way; I totally understand if you'd rather not, though.

**Comment by swj1442291549** [comment]
That would be great. 

I am happy to share my backup file for debug. Perhaps through your email, will do it tomorrow.

**Comment by fer0n** [comment]
That'd be perfect, thanks :) 
You can also delete everything except for the subscription data, I'm assuming that's the important bit in case it's related to that somehow.

**Comment by fer0n** [comment]
Thanks for sharing the backup, I've found the issue: they're being incorrectly identified as YouTube #shorts and you have #shorts set to discard.

I'll see if I can fix this, in the meantime you can set #shorts to "show" and they should appear.

**Comment by swj1442291549** [comment]
Great thanks for your effort. They do show up after the switch of shorts.

**Comment by swj1442291549** [comment]
I tested with build 142 and these videos are shown correctly even with #shorts discard.

**Comment by fer0n** [comment]
Build 142 is out now and should fix the detection for new videos.

Existing videos will stay the same, but you can unsubscribe the channel from the subscription list view (this should delete all existing videos you haven't marked as watched or ones that are still in the queue) and then resubscribe and reload.  

#Shorts are marked with an "#s" where the duration is on the thumbnail.
