### ISSUE TITLE
The search bar for subscriptions under Library Tab does not support Chinese keyword

### ISSUE THREAD

**Issue by swj1442291549** [fer0n/Unwatched#13]
The search bar for subscriptions (with "Search library" in text) does not support Chinese keyword, which means I could not switch to Chinese keyboard. 

Despite this, If I just paste Chinese characters into the search bar, the search function works as expected.

**Comment by fer0n** [comment]
thanks for pointing this out, I believe I've found a fix for this. It'll be in the next version
