### ISSUE TITLE
The arrow keys on the iPad keyboard do not support fast-forwarding or rewinding videos

### ISSUE THREAD

**Issue by swj1442291549** [fer0n/Unwatched#14]
The space key can pause/play the videos. Also, on the mac, the arrow keys is working fine.

**Comment by fer0n** [comment]
@swj1442291549 Could you check if this is fixed for you on v1.4.0?

**Comment by swj1442291549** [comment]
Sorry, this is still not working on iPad with Magic Keyboard.
