### ISSUE TITLE
Missing bookmark button on mac version

### ISSUE THREAD

**Issue by swj1442291549** [fer0n/Unwatched#16]

**Comment by fer0n** [comment]
I'm assuming you're talking about the bookmark button inside the player? You can always just right click the video inside the queue and select bookmark from there. Same for the open in in-App browser option.

The vertical space is more limited there and I don't want to cram a lot of in one line. Not sure what a good solution would be, perhaps a "more" button?

**Comment by swj1442291549** [comment]
Thanks for your reply.

That's interesting. I try to right click and did not find the bookmark (see attached). Did I miss something?
![CleanShot 2024-09-27 at 06 39 24@2x](https://github.com/user-attachments/assets/a629cbf0-542e-4c1c-a05f-41d0d3cdd9d4)

**Comment by fer0n** [comment]
The context menu will be identical in the next version across swipe or long press
