### ISSUE TITLE
Twitch Integration…

### ISSUE THREAD

**Issue by AYT04** [fer0n/Unwatched#17]
### Milestone!

In the future, it would be great if the app could include a Twitch integration, allowing users to watch, follow, and engage with their favorite channels directly within the app. This could be achieved through RSS feeds or what Xtra does.

https://github.com/lzeke0/TwitchRSS | not sure if this is helpful, but it would be a cool feature and nonetheless.

**Comment by fer0n** [comment]
Thanks for your feedback! It's reasonable suggestion, but this would be mean huge changes to the app – especially when interactions are supposed to be part of it. It is open source, though, so anyone who wants to can fork it and try to implement it.

I'd like to keep the app focused and straightforward. Maybe this changes in the future, but I currently don't have plans to include other video services. Sorry to disappoint.
