### ISSUE TITLE
Always show video duration

### ISSUE THREAD

**Issue by Tunous** [fer0n/Unwatched#18]
Right now, if I'm not mistaken, durations are only displayed above videos that I started watching. I would like to have this extended to non-started videos.

Often I'm using video length to decide whether to start watching a specific video. Having this information immediately visible would be useful.

**Comment by fer0n** [comment]
YouTube RSS feeds don't include video durations. Once the video loads in the player, the duration will appear.

For videos with chapters, the start time of the last chapter is used as an approximate duration, shown as the minimum "+" time.

The api does include the duration, but is rate limited. Sadly nothing I can do.
