### ISSUE TITLE
Incomplete videos list in subscriptions

### ISSUE THREAD

**Issue by mvmalyi** [fer0n/Unwatched#2]
Once a user subscribes to a channel, only a handful of videos is actually available within the app when that subscription is open. 

As an example, this is the last available video of minutephysics within the app:
![image](https://github.com/user-attachments/assets/daa59faf-3abf-4183-bea8-d190f1efb0ed)

Whereas the channel has quite a few more videos published earlier:
![image](https://github.com/user-attachments/assets/f1e37c82-1be4-4d04-b17d-d6d515eac8ac)

It would be nice to have them visible within Unwatched!

**Comment by fer0n** [comment]
How did you add the subscription? By pasting a channel url, rss feed, using the "add subscription" button inside the in-app browser?
