### ISSUE TITLE
Split the Queue: Single Videos and Playlists

### ISSUE THREAD

**Issue by demed86** [fer0n/Unwatched#20]
Again, I really like your app. I use it like intended: I put videos into the queue and watch them. Especially I like the 3x. But I also would like to watch larger playlists from YouTuber (older let's plays). But this fills my queue fast. 

My idea: When I add a playlist, don't add the single videos. Create a subqueue/playlist inside the playlist.

**Comment by fer0n** [comment]
I don't have plans to support anything things like multiple playlists or a more complex organization system, [Play](https://apps.apple.com/de/app/play-save-videos-watch-later/id1596506190) is doing a better job there than I ever could and has recently also added a dedicated player.

You could try to add the playlist in its entirety, remove everything from the queue again ("more" menu, clear above/below) and then manually pick out the videos as soon as you want to watch them by visiting the subscription detail view.
