### ISSUE TITLE
Low-resolution on macOS

### ISSUE THREAD

**Issue by cdf1982** [fer0n/Unwatched#22]
Hello and as always, thank you for Unwatched.

There's a thing that I noticed on the Mac Catalyst version since day one: the only resolution available, for any video, is the lowest one, usually 360p.

I assume this is due to the YouTube embed and that there's nothing that can be done about it, but I thought I'd ask.

![2024-11-11 19_56_27](https://github.com/user-attachments/assets/7c7a54e0-b5c3-454a-af2d-47faa8f7d715)

**Comment by fer0n** [comment]
Yes, I don't have any real control over that. What I'm already doing is changing the browser agent, which for some reason leads to the "auto" quality selection actually playing at a higher quality than 360p and judging from the screenshot that seems to be working.

**Comment by cdf1982** [comment]
Exactly, that's the other odd thing: despite what it says, it generally looks like a 720p video, and indeed it shows HD on the gear icon below the video.

Thanks for the reply, I appreciate you jump through a lot of hoops and I am very thankful!
