### ISSUE TITLE
tvOS app: YouTube App is required to watch videos

### ISSUE THREAD

**Issue by robert-stokes** [fer0n/Unwatched#23]
I am getting the above error when trying to play a video from my Queue in the Apple TV app, despite the YouTube app being installed. It has only started happening in recent days.

It doesn't occur with the same Queue on other devices (iPhone and iPad).

tvOS is the current latest version 18.1 and both the Unwatched and YouTube apps are updated to the latest versions.

Thanks,
Rob

**Comment by fer0n** [comment]
Thanks for reporting this, I've pushed a new version to TestFlight as well as the App Store. It should be there soon. As soon as it's out, could you check if that solved the issue for you?

**Comment by fer0n** [comment]
@robert-stokes fix should be out now, could you update and check if it's fixed?

**Comment by robert-stokes** [comment]
All working correctly on the tvOS app again! Many thanks for the fix.

**Comment by fer0n** [comment]
Great, thanks for checking :)
