### ISSUE TITLE
Video pauses and won't unpause when switching to another app

### ISSUE THREAD

**Issue by potatoDOTzip** [fer0n/Unwatched#29]
On my iPhone, when I have video playing (in the default view or in iOS fullscreen) and I switch to another app, the video stops playing. To get it to start again, I have to force quit the app and relaunch.
This is not an issue when using Picture in Picture

Thanks for such an amazing app!

**Comment by fer0n** [comment]
Does this happen immediately or only after some time? Do you happen to have a screen recording that demonstrates the issue? Thanks :)

**Comment by potatoDOTzip** [comment]
I can't figure out how to reproduce it 100% of the time, but it usually takes a few seconds to kick in. Here are two screen recordings.

https://github.com/user-attachments/assets/32f8fa90-bb81-4360-a057-371b22aca465
https://github.com/user-attachments/assets/b806b180-d9f9-4e4a-ada3-7b0ae5ef416a

**Comment by fer0n** [comment]
Thanks for sharing these, I'll look into it :)

**Comment by fer0n** [comment]
There's a new build out now which should fix this, could you take a look if it's working for you?

**Comment by potatoDOTzip** [comment]
Sorry if this is a silly question, but is that build available somewhere like TestFlight? Or do I need to build it myself in Xcode?

**Comment by fer0n** [comment]
My bad, I thought I specified it. It’s on TestFlight, you can join here if you want: https://testflight.apple.com/join/9RP0WzCR

**Comment by fer0n** [comment]
I haven't found a way to either keep playing audio or automatically enable pip when leaving the app.

What I could try is persisting the pip mode, perhaps that's possible. So that if you enable it once, it stays on and automatically enters pip when a new video starts playing. Is that something that would help?

**Comment by potatoDOTzip** [comment]
So if you finished a video in PiP, the next one would automatically start in PiP as well? Because that sounds useful

**Comment by fer0n** [comment]
Not sure if that’s possible, but that’s what I was considering. I don’t think it’s going to be possible to have it continue while you’re outside the app, but it should work with the app open

**Comment by fer0n** [comment]
There's a new build (176) out now with the persisted pip setting, feel free to take a look. I'll close this one as the playback issue seems to be resolved.
