### ISSUE TITLE
Blank rows in Queue

### ISSUE THREAD

**Issue by MaxPelly** [fer0n/Unwatched#3]
After adding some videos to queue and then watching them blank lines remain in the queue visible as a two separating bars separated by just under a cm of blank space. These can not be interacted with through tapping or swiping and seem to appear both above and below actual videos, remaining when all videos are watched. 

They can be removed by by swiping on an actual video in the queue and using clear all above/below, though this requires two passes, the first crashes the app with the blank entries remaining while the second actually removes them.

(Will post pictures once they reappear)

**Comment by fer0n** [comment]
Thanks for reporting it, what iOS version are you on?

I have seen this pop up on the iOS 18 betas, but I haven't yet looked into it too much as I'm hoping that the next one might fix it.

**Comment by MaxPelly** [comment]
Sorry should have said, I'm on the latest 18.0 beta on an 11 inch M1 iPad pro

Max Pelly (He/Him)
PhD Student
https://rost.wp.st-andrews.ac.uk


School of Physics and Astronomy
University of St Andrews
North Haugh
St Andrews, Fife
KY169SS
UK
________________________________

**Comment by fer0n** [comment]
Thanks! I'll wait until the next beta, if it's still an issue then I'll take a closer look at what's going on.

**Comment by fer0n** [comment]
I took a slightly closer look and it seems like empty SwiftData relationships are an [issue for others on iOS 18 as well](https://developer.apple.com/forums/thread/759364). I'm still hoping this will get fixed by Apple (alongside quite a few other SwiftData issues that I've been seeing).

**Comment by psomhorst** [comment]
> They can be removed by by swiping on an actual video in the queue and using clear all above/below

Thanks for this temporary fix! Indient figure this one out yet. 

Just for completeness, I attached a screenshot on the latest public beta of iOS 18. 

![image](https://github.com/user-attachments/assets/e5f3dd7c-770e-41a4-b260-27a178d04356)

**Comment by fer0n** [comment]
Uf that looks very rough, I haven't seen it before this bad yet. I'm not sure if that improves it, but if you go back to the Home Screen (don't force quit) after loading new videos, it persists the thumbnails. Perhaps that helps swiftdata to keep them around. Not sure though, sorry.

**Comment by psomhorst** [comment]
> Uf that looks very rough, I haven't seen it before this bad yet. I'm not sure if that improves it, but if you go back to the Home Screen (don't force quit) after loading new videos, it persists the thumbnails. Perhaps that helps swiftdata to keep them around. Not sure though, sorry.

How does that solve the issue? I'm not missing thumbnails, the blank lines should be removed instead. 

Since it's possible to manually remove the lines by clearing above/below a video, isn't it possible to clear played videos automatically?

**Comment by fer0n** [comment]
> How does that solve the issue? I'm not missing thumbnails, the blank lines should be removed instead.

Since it's possible to manually remove the lines by clearing above/below a video, isn't it possible to clear played videos automatically?

The discussion on the Apple forums is also about adding data; this problem is about videos being removed from the queue.

**Comment by fer0n** [comment]
> How does that solve the issue? I'm not missing thumbnails, the blank lines should be removed instead.

It won't fix the issue, but it might help avoid it for the time being. Perhaps it will do nothing, though. I'm not sure if there's even anything I can do, as this is a very basic SwiftData feature that isn't working right. The problem seems to be that SwiftData looses relationships to other models. The QueueEntry model has relationship to the Video. The empty line you're seeing means the entry is still there, but the connection to the video is missing.

While the app is open, new videos have their thumbnails in memory, when you close the app they will be persisted. I was thinking maybe the additional cached image relationship might help it somehow.

> Since it's possible to manually remove the lines by clearing above/below a video, isn't it possible to clear played videos automatically?

If you enable "continuous play", the video will be marked watched automatically. The empty lines don't mean the video has been watched, the relationship is just broken.

> The discussion on the Apple forums is also about adding data; this problem is about videos being removed from the queue.

The missing relationship is mentioned there as well, that's what I meant.

**Comment by psomhorst** [comment]
I think I failed to get my point across. I think you're saying that the lines represents videos that *should* be there. What I'm trying to get across is that these videos are *already watched*, so they should not be in the queue. The lines stay there after a video has been watched and finished.

**Comment by MaxPelly** [comment]
I'd partially agree with that.
I definitely do not notice videos that should be in the queue disappearing.
The blanks lines seem to show up after a video is removed from the queue. Seems to me to be more of a video is dismissed, seems to go away ok and then the blank lines sometime appear some time later

**Comment by MaxPelly** [comment]
Fortunately it's only a mild annoyance (which is to be expected when running the iOS betas) and the app is otherwise amazing! Has totally changed my YouTube use!

**Comment by MaxPelly** [comment]
Turns out I was wrong, just saw the tile from a video disappear in the queue as I was watching it leaving behind a blank lines

**Comment by fer0n** [comment]
> What I'm trying to get across is that these videos are already watched, so they should not be in the queue.

@psomhorst I think that's a result of the queueEntry-video relationship being broken so you definitely have point. The connection breaks, you watch the video, but since the connection is broken it can't remove the queue entry anymore.

**Comment by fer0n** [comment]
I've just released v1.2 (128) on TestFlight, I haven't seen empty rows in a while, perhaps it's fixed. I also made it possible to remove empty rows if they do show up. 

Let me know if you still see them on that version.

**Comment by MaxPelly** [comment]
Possibly being thick but is there a link to the TestFlight anywhere? (Though no pressure if its private, quit happy to wait for the release)

**Comment by fer0n** [comment]
Sorry, I thought I posted it already.

https://testflight.apple.com/join/9RP0WzCR

**Comment by fer0n** [comment]
Perhaps iCloud sync fixes the issue somehow, could be related to that.

**Comment by MaxPelly** [comment]
Haven't seen any blank rows since installing the TestFlight, looks like its solved!

**Comment by fer0n** [comment]
@MaxPelly Sorry to open this again, have you changed your iCloud sync setting? I wonder if it's actually fixed for all cases.

**Comment by MaxPelly** [comment]
Don't think so,  I have sync via iCloud off and back up to iCloud drive on (which I think is the default, don't remember touching them)

**Comment by fer0n** [comment]
Thanks, looks like that may have done it them :)
