### ISSUE TITLE
Unwatched crashes when clicking on video title

### ISSUE THREAD

**Issue by acrostich** [fer0n/Unwatched#30]
Version 1.5.0 (172) on macOS 15.1.1 (24B91)

When clicking the video title to get the description and chapters (if any) Unwatched crashes. I've tried this on two short videos and it crashes Unwatched on both. It worked fine in previous versions.

**Comment by fer0n** [comment]
I‘ll take a Look, thanks for reporting this :)

**Comment by fer0n** [comment]
I've pushed a new build with a potential fix, could you be so kind to check if it's working now?

**Comment by acrostich** [comment]
Yes and no!

It's fixed when clicking on the title I was clicking on yesterday. However I've since noticed the little dots at the bottom of the screen and that one can slide left to have some more info. When clicking on the title on that second page/tab (not sure what's the right term for this zone), then Unwatched crashes. So you probably have two different set of code for these two titles and only fixed the issue in one place.

**Comment by fer0n** [comment]
Will be fixed in the next build, thanks. That currently opens the video on YouTube, not sure if it makes sense to have that there, though.

**Comment by acrostich** [comment]
Thank you for these quick fixes and Unwatched in general. 

Maybe it would make more sense in the video’s contextual menu?  It would also be useful to have the option to reload the video (sometimes i get asked to sign in YT; changing the exit node of my VPN fixes that, but i then have to close and reopen Unwatched so the video is reloaded.)

**Comment by fer0n** [comment]
That option is already in the context menu of each list item as well as under the "..." button. There's also an option to reload the video, is that not what you're looking for?

**Comment by acrostich** [comment]
Yes it is. I had missed that menu. Perfect. Thank you.

**Comment by fer0n** [comment]
New build (174) should be out now, could you check if it's working correctly? :)

**Comment by acrostich** [comment]
Just checked. It is working in this latest build. Thank you.
