### ISSUE TITLE
Suggestion: 'jkl' keyboard shortcut alternatives (or defaults for iPad) for seeking and pause/play

### ISSUE THREAD

**Issue by attaboyBrad** [fer0n/Unwatched#31]
If you can't get the arrow key keyboard shortcuts for 'seek' to work on iPad, you might consider 'j' and 'l' as alternatives, which would be consistent with [the player shortcuts from the Youtube web player](https://support.google.com/youtube/answer/7631406?hl=en).  Hard to go wrong when it's what Youtube uses itself.

**Comment by fer0n** [comment]
I've actually just pushed a new build with those exact shortcuts in addition to the arrow keys, as they're not working on the iPad.
