### ISSUE TITLE
Youtube button crashes Unwatched

### ISSUE THREAD

**Issue by acrostich** [fer0n/Unwatched#33]
To reproduce (on macOS):

1/ Go to Library tab
2/ Click on any subscribed feed
3/ Click on the Youtube icon (just right of the Subscribed button)

Unwatched crashes.

BTW I went there trying to figure out what URL one my feed was using as it is showing mostly shorts and I wanted to check if I was subscribed to a playlist instead of the main feed. Is there a way to reveal the URL of a subscribed feed?

**Comment by acrostich** [comment]
It also happens when opening a video, pressing the ... and selecting 'View on YouTube'.

**Comment by fer0n** [comment]
Will be fixed in the next build (see #30)
