### ISSUE TITLE
Feature request: have the 'hide #shorts' setting per feed

### ISSUE THREAD

**Issue by acrostich** [fer0n/Unwatched#34]
Use case: for most feeds I like to watch the shorts, however for some they just advertise the full videos and I'd prefer to avoid these. 

Unwatched has a Hide #Shorts setting but it's a global one. It would be helpful to have this setting instead on a per feed basis.

**Comment by fer0n** [comment]
I've been meaning to get to this for some time, definitely makes sense to have that option per channel.

**Comment by fer0n** [comment]
There's a new build out now with per-channel shorts settings, could you let me know if you're running into any issues with it?

**Comment by acrostich** [comment]
Seems to work from a quick test. Thank you for addressing this.

**Comment by fer0n** [comment]
If something's not working feel free to open another issue :)
