### ISSUE TITLE
Are there different types of YouTube subscriptions/channels?

### ISSUE THREAD

**Issue by mcleod5000** [fer0n/Unwatched#36]
Hi there, is it a problem on my side (wrong settings or something like that) or are there different types of Channels on YT? I would like all my videos to look like the one on the bottom here. But there are some channels that still show the suggested videos from the YouTube site next to the video. Any suggestions? Thanks in advance!

![compare](https://github.com/user-attachments/assets/2aab0eef-cec8-465b-98c1-783c3d4ee937)

**Comment by mcleod5000** [comment]
I think I should have read the EMail & FAQ section on the settings page. It is a YT channel setting, right?

**Comment by mcleod5000** [comment]
I think I should have read the EMail & FAQ section on the settings page. It is a YT channel setting, right?

**Comment by fer0n** [comment]
Yes, not sure if it’s per channel or per video, but there’s a setting that lets channels turn off the embedded player, in which case Unwatched is falling back to the website
