### ISSUE TITLE
Are there plans to import Playlists?

### ISSUE THREAD

**Issue by rickyrodmac** [fer0n/Unwatched#4]
I'm really enjoying the app and it would really be useful if  it could import playlists.

**Comment by fer0n** [comment]
Importing playlists is already possible. Either visit a playlist (the actual list, not the first video) in the in-App browser, or simply paste the playlist url into the text field on top of the library. You'll be able to choose if you want to follow the playlist or add the playlist content to your queue.

I'll change the wording inside the text box to make this clearer in the future.
