### ISSUE TITLE
iPadOS 18.1 beta 4 - crash on launch

### ISSUE THREAD

**Issue by serene-volt** [fer0n/Unwatched#9]
After updating to iPadOS 18.1 beta 4, the app will consistently crash on launch. I have uninstalled the app and reinstalled, but the issue persists.

For what it’s worth, the app launches and works fine on iOS 18 using the same user data and “Sync via iCloud” turned on both devices.

**Comment by fer0n** [comment]
I've just submitted a fix in 1.2.1 (133), it's waiting on App Review. If you haven't already, you can join the TestFlight here: https://testflight.apple.com/join/9RP0WzCR

**Comment by chrisjniles** [comment]
I have both iOS and iPadOS 18.1 installed and I installed the TestFlight version of Unwatched on both devices and the app still crashes on launch on both devices.

**Comment by fer0n** [comment]
@chrisjniles it's still in App Review, it's not on TestFlight yet. The version is v1.2.1 (133)

**Comment by chrisjniles** [comment]
My mistake, thank you for the clarification

**Comment by fer0n** [comment]
@chrisjniles @serene-volt TestFlight build is out now, could you confirm if it's working again?

**Comment by serene-volt** [comment]
@fer0n Looking good on my end so far. No crash on launch.
